### ISSUE TITLE
Nach Update auf 0.6.1 keine Funktion mehr

### ISSUE THREAD

**Issue by Timo1706** [Pmant/ioBroker.harmony#10]
![harmony](https://cloud.githubusercontent.com/assets/25309153/22626696/10e1e20c-ebb4-11e6-8caa-241b8142ff99.JPG)
Nach update nur noch Fehler und keine Verbindung zum Hub.
Was mache ich falsch?

**Comment by tm8** [comment]
Ich kann den Adapter nicht installieren, bringt folgende Meldung, was kann ich tun?

`$ ./iobroker url "https://github.com/Pmant/ioBroker.harmony/tarball/master" harmony
install https://github.com/Pmant/ioBroker.harmony/tarball/master
npm install https://github.com/Pmant/ioBroker.harmony/tarball/master --production --prefix "/opt/iobroker" (System call)
npm
 WARN engine harmonyhubjs-client@1.1.10: wanted: {"npm":">=3.0.0"} (current: {"node":"4.6.2","npm":"2.15.11"})
npm WARN deprecated
 node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm WARN deprecated node-xmpp-jid@2.3.0: use @xmpp/jid package <https://www.npmjs.com/package/@xmpp/jid>`

Alles im iobroker auf dem aktuellen Stand.

**Comment by Pmant** [comment]
Das ist kein Fehler, nur warnings. solte trotzdem installiert werden.
