### ISSUE TITLE
How to specify IP for hub?

### ISSUE THREAD

**Issue by ErAzOr2k** [Pmant/ioBroker.harmony#13]
Hi,

My Harmony Hub is attached in 10.0.1.0 network. ioBroker is running in 10.0.3.0 network.
Because of the two different networks, the harmony adapter is not able to find my harmony hub.

Is there a way to specify the harmony hub directly by ip address? I coulnd't find any setting for that :/

**Comment by Pmant** [comment]
Im sorry but the Adapters life cycle is build around the SSDP Discovery, I'm afraid you can't just put in the IP. Maybe you can forward the Multicast traffic to you network?
