### ISSUE TITLE
IObroker stops working

### ISSUE THREAD

**Issue by bradock77** [Pmant/ioBroker.harmony#17]
I made long time tests and as far as run Version 0.70 (tested also with different JS versions 0.5.3 and 1.20) IoBroker stopped working. (deamon stops)
I am currently back on adapter version 0.62 to verify if this is more stable.

If I stop Harmony Adapter, I have no stop of IoBroker deamon.

**Comment by Pmant** [comment]
I can't reproduce this error, works fine with 0.7.1 and newest js-controller 1.2.0. Any logs?

**Comment by bradock77** [comment]
Hallo Pmant,

Ich denke wir können uns auch auf deutsch austauschen, oder?

Habe im Forum schon einen Thread mit Logs etc..

http://forum.iobroker.net/viewtopic.php?f=8&t=8450


Kind regards /  viele Grüße.

Sascha Trumpp




Disclaimer
The information contained in this message is confidential or protected by law. If you are not the intended recipient, please contact the sender and delete this message. Any unauthorised copying of this message or unauthorised distribution of the information contained herein is prohibited.
Diese E-Mail enthaelt vertrauliche oder rechtlich geschuetzte Informationen. Wenn Sie nicht der beabsichtigte Empfaenger sind, informieren Sie bitte sofort den Absender und loeschen Sie diese E-Mail. Das unbefugte Kopieren dieser E-Mail oder die unbefugte Weitergabe der enthaltenen Informationen ist nicht gestattet.

Am 29.10.2017 um 13:35 schrieb Pmant <notifications@github.com<mailto:notifications@github.com>>:


I can't reproduce this error, works fine with 0.7.1 and newest js-controller 1.2.0. Any logs?
