### ISSUE TITLE
Enhancement: Current Activity Remote Buttons

### ISSUE THREAD

**Issue by foxriver76** [Pmant/ioBroker.harmony#22]
It would be a nice feature if the user has the possibility to use the buttons of the remote control for the current activity in ioBroker. 

e.g. by pressing pause on my mobile phone or my remote, it sends the pause button to the tv when i have triggered the internal Netflix app of my smart tv. Otherwise when I triggered my Amazon Video activity on Fire TV, the same button sends the pause command to the Fire TV while this activity is triggered. 

If this isn't possible with the Harmony API give me a short feedback please.

**Comment by Pmant** [comment]
I don't know if  this is possible with the undocumented API. However, you can easily rebuild the desired behaviour in ioBroker.

**Comment by siggi85** [comment]
It is possible to build this in iobroker but the maingoal of harmony is to let the multimedia logic inside the harmony hub. When it is possible someday i would love to see this feature in this module. :) Thanks for our time.
