### ISSUE TITLE
After JS Controller update 1.4.2 the adapter doesn´t work

### ISSUE THREAD

**Issue by misanorot** [Pmant/ioBroker.harmony#24]
This log pops up after the update---

> Caught | 2018-04-23 21:40:28.198 | error | by controller[0]: at Connection.emit (events.js:211:7)
> -- | -- | -- | --
> Caught | 2018-04-23 21:40:28.198 | error | by controller[0]: at emitOne (events.js:116:13)
> Caught | 2018-04-23 21:40:28.197 | error | by controller[0]: at Client.onStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:222:8)
> Caught | 2018-04-23 21:40:28.197 | error | by controller[0]: at Client._handleStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:228:12)
> Caught | 2018-04-23 21:40:28.197 | error | by controller[0]: at Client.emit (events.js:211:7)
> Caught | 2018-04-23 21:40:28.197 | error | by controller[0]: at emitOne (events.js:116:13)
> Caught | 2018-04-23 21:40:28.197 | error | by controller[0]: at HarmonyClient.handleStanza (/opt/iobroker/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
> Caught | 2018-04-23 21:40:28.197 | error | by controller[0]: at Array.forEach ()
> Caught | 2018-04-23 21:40:28.197 | error | by controller[0]: at /opt/iobroker/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
> Caught | 2018-04-23 21:40:28.197 | error | by controller[0]: at JSON.parse ()
> Caught | 2018-04-23 21:40:28.197 | error | by controller[0]: SyntaxError: Unexpected end of JSON input
> harmony.0 | 2018-04-23 21:40:28.187 | info | terminating
> harmony.0 | 2018-04-23 21:40:28.175 | info | terminating
> harmony.0 | 2018-04-23 21:40:28.175 | error | at Connection.emit (events.js:211:7)
> harmony.0 | 2018-04-23 21:40:28.175 | error | at emitOne (events.js:116:13)
> harmony.0 | 2018-04-23 21:40:28.175 | error | at Client.onStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:222:8)
> harmony.0 | 2018-04-23 21:40:28.175 | error | at Client._handleStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:228:12)
> harmony.0 | 2018-04-23 21:40:28.175 | error | at Client.emit (events.js:211:7)
> harmony.0 | 2018-04-23 21:40:28.175 | error | at emitOne (events.js:116:13)
> harmony.0 | 2018-04-23 21:40:28.175 | error | at HarmonyClient.handleStanza (/opt/iobroker/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
> harmony.0 | 2018-04-23 21:40:28.175 | error | at Array.forEach ()
> harmony.0 | 2018-04-23 21:40:28.175 | error | at /opt/iobroker/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
> harmony.0 | 2018-04-23 21:40:28.175 | error | at JSON.parse ()
> harmony.0 | 2018-04-23 21:40:28.175 | error | SyntaxError: Unexpected end of JSON input
> harmony.0 | 2018-04-23 21:40:28.175 | error | uncaught exception: Unexpected end of JSON input
> harmony.0 | 2018-04-23 21:40:28.130 | info | connected to Wohnzimmer
> harmony.0 | 2018-04-23 21:40:25.796 | info | connecting to Wohnzimmer
> harmony.0 | 2018-04-23 21:40:25.791 | info | discovered Wohnzimmer
> harmony.0 | 2018-04-23 21:40:24.537 | info | searching for Harmony Hubs...

**Comment by Blackei** [comment]
Hi,
I have the same Problem.

**Comment by Pmant** [comment]
maybe #25?

**Comment by misanorot** [comment]
After the 9.2 update, the same issue:
`

host.ioBroker | 2018-06-26 20:36:45.910 | error | instance system.adapter.harmony.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2018-06-26 20:36:45.910 | error | by controller[0]: at Connection.emit (events.js:211:7)
Caught | 2018-06-26 20:36:45.910 | error | by controller[0]: at emitOne (events.js:116:13)
Caught | 2018-06-26 20:36:45.910 | error | by controller[0]: at Client.onStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:222:8)
Caught | 2018-06-26 20:36:45.910 | error | by controller[0]: at Client._handleStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:228:12)
Caught | 2018-06-26 20:36:45.910 | error | by controller[0]: at Client.emit (events.js:211:7)
Caught | 2018-06-26 20:36:45.910 | error | by controller[0]: at emitOne (events.js:116:13)
Caught | 2018-06-26 20:36:45.910 | error | by controller[0]: at HarmonyClient.handleStanza (/opt/iobroker/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
Caught | 2018-06-26 20:36:45.910 | error | by controller[0]: at Array.forEach (<anonymous>)
Caught | 2018-06-26 20:36:45.910 | error | by controller[0]: at /opt/iobroker/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
Caught | 2018-06-26 20:36:45.910 | error | by controller[0]: at JSON.parse (<anonymous>)
Caught | 2018-06-26 20:36:45.910 | error | by controller[0]: SyntaxError: Unexpected end of JSON input
harmony.0 | 2018-06-26 20:36:45.902 | info | terminating
harmony.0 | 2018-06-26 20:36:45.890 | info | terminating
harmony.0 | 2018-06-26 20:36:45.889 | error | at Connection.emit (events.js:211:7)
harmony.0 | 2018-06-26 20:36:45.889 | error | at emitOne (events.js:116:13)
harmony.0 | 2018-06-26 20:36:45.889 | error | at Client.onStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:222:8)
harmony.0 | 2018-06-26 20:36:45.889 | error | at Client._handleStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:228:12)
harmony.0 | 2018-06-26 20:36:45.889 | error | at Client.emit (events.js:211:7)
harmony.0 | 2018-06-26 20:36:45.889 | error | at emitOne (events.js:116:13)
harmony.0 | 2018-06-26 20:36:45.889 | error | at HarmonyClient.handleStanza (/opt/iobroker/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
harmony.0 | 2018-06-26 20:36:45.889 | error | at Array.forEach (<anonymous>)
harmony.0 | 2018-06-26 20:36:45.889 | error | at /opt/iobroker/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
harmony.0 | 2018-06-26 20:36:45.889 | error | at JSON.parse (<anonymous>)
harmony.0 | 2018-06-26 20:36:45.889 | error | SyntaxError: Unexpected end of JSON input
harmony.0 | 2018-06-26 20:36:45.889 | error | uncaught exception: Unexpected end of JSON input
harmony.0 | 2018-06-26 20:36:45.852 | info | connected to Wohnzimmer
harmony.0 | 2018-06-26 20:36:43.629 | info | connecting to Wohnzimmer
harmony.0 | 2018-06-26 20:36:43.626 | info | discovered Wohnzimmer
harmony.0 | 2018-06-26 20:36:42.375 | info | searching for Harmony Hubs...
harmony.0 | 2018-06-26 20:36:42.358 | info | starting. Version 0.9.2 in /opt/iobroker/node_modules/iobroker.harmony, node: v8.11.1

`

**Comment by Pmant** [comment]
This doesn't happen on my setup (raspbian node 6).
Btw. the error is thrown in [harmonyhubjs-client](https://github.com/swissmanu/harmonyhubjs-client/blob/develop/lib/harmonyclient.js).
