### ISSUE TITLE
Do not generate objectds/tates with ",", "?", "[" and "]"  or " or ' or spaces in it!!

### ISSUE THREAD

**Issue by Apollon77** [Pmant/ioBroker.harmony#25]
see https://github.com/ioBroker/ioBroker.js-controller/issues/198

According to observations in forum sometimes states are created with "*" as last character or such. This should be avoided and replaced. Else the adapter with ot work with js-controller 1.4.2+

**Comment by Apollon77** [comment]
Spaces added as forbidden too.

**Comment by Apollon77** [comment]
*ping* we plan to replease js-controller 1-4-2 to stable soon so "*" are already staring to be problematic!!

**Comment by Pmant** [comment]
been extremely busy lately, is there a final function / regex to replace all problematic symbols?

**Comment by Pmant** [comment]
should be fixed in 0.9.1, still needs testing. Tested an activity name containing * and some remote buttons. Did not test hub names.

**Comment by WolfspiritM** [comment]
Spaces are missing from the forbidden chars regex. 
Now it creates IDs like:
"harmony.0.Harmony Hub 2.activities.Watch Fire TV"

**Comment by Apollon77** [comment]
We decided to re-allow spaces :-)

**Comment by Apollon77** [comment]
@PMant: you may want to answer https://forum.iobroker.net/viewtopic.php?f=20&t=15112 ?!
