### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by misanorot** [Pmant/ioBroker.harmony#26]
I wanted reinstall the adapter but he does´t. The install log is: 

> Fertig mit Fehler: reading io-package.json Error: ENOENT: no such file or directory, open 'null/io-package.json'

**Comment by Pmant** [comment]
can anyone confirm this? Install went through on my ioBroker setup.

**Comment by misanorot** [comment]
Perhaps it is a uninstall issue from the version before. I will check it tomorrow...

**Comment by misanorot** [comment]
At the main system and the development system the same problems with this log in the console:

`

  |   |   |  
-- | -- | -- | --
iobroker | 2018-06-26 20:11:24.555 | info | exit 20
iobroker | 2018-06-26 20:11:24.550 | error | host.ioBroker error: reading io-package.json Error: ENOENT: no such file or directory, open 'null/io-package.json'
iobroker | 2018-06-26 20:11:24.549 | info | host.ioBroker create instance harmony
iobroker | 2018-06-26 20:11:24.517 | info | npm ERR! /root/.npm/_logs/2018-06-26T18_11_24_502Z-debug.log
iobroker | 2018-06-26 20:11:24.517 | info | npm ERR! A complete log of this run can be found in:
iobroker | 2018-06-26 20:11:24.494 | info | npm ERR! Please check if you have git installed and in your PATH.
iobroker | 2018-06-26 20:11:24.493 | info | npm ERR! Failed using git.
iobroker | 2018-06-26 20:11:24.493 | info | npm ERR!
iobroker | 2018-06-26 20:11:24.493 | info | undefinednpm ERR! No git binary found in $PATH
iobroker | 2018-06-26 20:11:24.491 | info | npm ERR!
iobroker | 2018-06-26 20:11:24.490 | info | ERR!
iobroker | 2018-06-26 20:11:24.488 | info | npm
iobroker | 2018-06-26 20:11:24.487 | info | undefined ls-remote -h -t https://github.com/swissmanu/ltx.git
iobroker | 2018-06-26 20:11:24.487 | info | ERR!
iobroker | 2018-06-26 20:11:24.487 | info |  
iobroker | 2018-06-26 20:11:24.486 | info | npm
iobroker | 2018-06-26 20:11:24.486 | info | Error while executing:
iobroker | 2018-06-26 20:11:24.485 | info | ERR!
iobroker | 2018-06-26 20:11:24.484 | info |  
iobroker | 2018-06-26 20:11:24.482 | info | npm
iobroker | 2018-06-26 20:11:24.480 | info | ENOGIT
iobroker | 2018-06-26 20:11:24.479 | info | code
iobroker | 2018-06-26 20:11:24.478 | info |  
iobroker | 2018-06-26 20:11:24.477 | info | ERR!
iobroker | 2018-06-26 20:11:24.476 | info |  
iobroker | 2018-06-26 20:11:24.475 | info | npm
iobroker | 2018-06-26 20:11:23.607 | info | node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
iobroker | 2018-06-26 20:11:23.606 | info | deprecated
iobroker | 2018-06-26 20:11:23.605 | info |  
iobroker | 2018-06-26 20:11:23.604 | info | WARN
iobroker | 2018-06-26 20:11:23.603 | info |  
iobroker | 2018-06-26 20:11:23.602 | info | npm
iobroker | 2018-06-26 20:11:16.805 | info | npm install iobroker.harmony --production --save --prefix "/opt/iobroker" (System call)
iobroker | 2018-06-26 20:11:16.590 | info | NPM version: 6.0.0
iobroker | 2018-06-26 20:11:16.052 | info | add harmony

`
