### ISSUE TITLE
Sometimes connection drops and doesn't reconnect

### ISSUE THREAD

**Issue by WolfspiritM** [Pmant/ioBroker.harmony#29]
Hi,

Sometimes ioBroker loses connection to one of my hubs (not sure if it's cause of bad connection or something else) until I restart the adapter.

Here is the log:

```

harmony.0 | 2018-08-24 03:19:38.679 | warn | error changing activity, client offline
-- | -- | -- | --
harmony.0 | 2018-08-24 01:53:37.106 | warn | could not connect to Schlafzimmer: Error: Timed out after 5000 ms
harmony.0 | 2018-08-24 01:53:30.102 | info | connecting to Schlafzimmer
harmony.0 | 2018-08-24 01:53:30.082 | debug | hub initialized
harmony.0 | 2018-08-24 01:53:29.954 | info | discovered Schlafzimmer
harmony.0 | 2018-08-24 01:53:28.462 | warn | lost Schlafzimmer
harmony.0 | 2018-08-24 01:52:52.200 | warn | could not connect to Schlafzimmer: Error: Timed out after 5000 ms
harmony.0 | 2018-08-24 01:52:45.173 | info | connecting to Schlafzimmer
harmony.0 | 2018-08-24 01:52:45.132 | debug | hub initialized
harmony.0 | 2018-08-24 01:52:45.076 | info | discovered Schlafzimmer
harmony.0 | 2018-08-24 01:52:43.501 | debug | xmpp offline
harmony.0 | 2018-08-24 01:52:43.493 | debug | xmpp offline
harmony.0 | 2018-08-24 01:52:43.455 | info | client ended: Schlafzimmer
harmony.0 | 2018-08-24 01:52:43.454 | debug | xmpp offline
harmony.0 | 2018-08-24 01:52:43.427 | warn | lost Schlafzimmer

```

While the hub is discovered it would maybe be helpful to reconnect to it in intervals to make sure it stays connected?!

**Comment by foxriver76** [comment]
You could try the github version from my fork: https://github.com/foxriver76/ioBroker.harmony 

The normal behaviour is that it will try to connect again every time the hub is discovered again. But the discovery is implemented in another package. My fork uses newer dependencies, so maybe this bug is fixed.

**Comment by WolfspiritM** [comment]
@foxriver76 Thanks. I think the relevant code is commented out in your fork so it might work better, but I still think that in some cases it might fail.

The reason why it breaks is that the hub stays discovered in my case. The relevent part is:
https://github.com/Pmant/ioBroker.harmony/blob/master/harmony.js#L297

It has a timeout of 5 seconds (I'm not sure what the default is in your fork as timeout is commented out but I assume that there still is a timeout). After that it fails (catched with "could not connect to ...") and just stops the client. The hub itself stays discovered in my case and so it won't try to reconnect at all. I think if the connection fails a setTimeout should start that tries to reconnect a few seconds later.

**Comment by foxriver76** [comment]
Thanks for the explanation -- I will have a closer look at it and will try to fix the problem.

**Comment by foxriver76** [comment]
If the issue still exists with 0.10.0 please reopen @WolfspiritM
