### ISSUE TITLE
Set ObjectName manually

### ISSUE THREAD

**Issue by Kuddel071089** [Pmant/ioBroker.harmony#36]
Since version 0.9.3 the dataobject name is "harmony.0.Harmony Hub".

Befor version 0.9.3 the dataobject name was "harmony.0.Harmony_Hub".

For updating my adapter to the newest version, i must change all scripts that are using the dataobject "harmony.0.Harmony_Hub.activities.currentActivity".

Maybe ist possible to set the dataobject-name in the adapter config?

**Comment by foxriver76** [comment]
It has underscores in current GitHub Version again.

**Comment by foxriver76** [comment]
Which is also latest tomorrow
