### ISSUE TITLE
Twice commands since new WS/Api

### ISSUE THREAD

**Issue by Strobelix80** [Pmant/ioBroker.harmony#43]
Since changing the adapter to Websocket or new API for example Volume commands were sent twice. 
Returning to XMPP Version everything works fine
(Of course tested with same new HUB Firmware which enables XMPP for developers)

**Comment by Pmant** [comment]
to what value (true, 1, 100, 1000?) did you set the volume state?

**Comment by Strobelix80** [comment]
I set it to 1

**Comment by Pmant** [comment]
Could you do me a favor and press volume up in the smartphone app once? I have to know if the APP does it different.

**Comment by Strobelix80** [comment]
With the harmony ios App it only triggers once

**Comment by Pmant** [comment]
There is a new Version 1.1.2 on GitHub that may fix this. Please check and leave a comment if it fixes your problem.

**Comment by Strobelix80** [comment]
Thank you. I've tested 1.1.2 but still the same issue. Returning to 1.0.0 it works fine.

**Comment by Pmant** [comment]
Please check version 1.1.4

**Comment by Strobelix80** [comment]
Works now! Thanks a lot
