### ISSUE TITLE
activity's not actual

### ISSUE THREAD

**Issue by crasythom** [Pmant/ioBroker.harmony#44]
Seit der Version 1.1. inkl. 1.1.1 aktualisieren sich die Aktivitäten nicht mehr, obwohl der Adapter verbunden ist. Deinstallation und Neuinstallation wurde schon versucht. IP-Adresse und Subnetz 255.255.255.0 wurden eingetragen. Die letzte Änderung der Werte fand zum Zeitpunkt der Installation statt. Die Aktivitäten starten auch nicht, wenn eine 1 geschrieben wird.

Since version 1.1. Including 1.1.1, the activities no longer refresh even though the adapter is connected. Deinstallation and reinstallation has already been tried. IP address and subnet 255.255.255.0 have been entered. The last change of values ​​occurred at the time of installation. The activities do not start even if a 1 is written.

**Comment by Pmant** [comment]
Bitte mal posten was im LOG steht beim start des Adapter und bei Änderungen an den Aktivitäten.

**Comment by Pmant** [comment]
Der Adapter findet den Hub nicht, Grün bedeutet nur, dass der Adapter korrekt gestartet ist. An diesem Teil des Adapters hat sich zu vorher eigentlich nichts geändert. Du kannst mal versuchen, das Subnet auf die IP deines Hubs zu stellen, dann gibt es weniger Probleme mit Firewalls und Routern. Du kannst dann aber nur diesen einen Hub nutzen.

**Comment by crasythom** [comment]
Super! Mit der IP im Subnetz funktioniert es. Mehr als einen HUB habe ich sowieso nicht :-)
Komisch ist aber, dass es mit der Version 0.9.3 noch funktioniert hat. Habe extra noch einen alten iobroker-Server (VM auf QNAP) gestartet. Da gab es mit dem Adapter keine Probleme. Bis zu dem Update auf 1.1.0 hat es auch auf meinem neuen Server (Proxmox VM) funktioniert.
Danke trotzdem. Meine Frau bekommt sonst einen Vogel, wenn Sie die Steckdose vom Fernseher vorher immer mit der App anschalten muss. Jetzt kann ich diese wieder über ioBroker anschalten wenn die entsprechende Aktivität gestartet wird.
