### ISSUE TITLE
Hub sendet manche Befehle doppelt.

### ISSUE THREAD

**Issue by FlexerJR** [Pmant/ioBroker.harmony#45]
Habe meinen Hub neu aufgesetzt. 
Aktuelle Hub Software ist 4.15.206
Adapter 1.1.0

Gibt man den Befehl einmal nach Links oder Rechts oder Volume Up oder Down dann erscheint folgendes im Log

sending command: Samsung_TV:VolumeUp
sending command: undefined

Das hat zur Folge, dass der Befehl 3 mal ausgeführt wird. 3mal rechts 3VolUp 3Mal Vol Down

Beste Grüße

**Comment by foxriver76** [comment]
Probier mal die 1.1.5, sollte @Pmant gefixt haben.

**Comment by foxriver76** [comment]
Kommt auf den eingestellten Verwahrungaort an. Bei latest ist sie da, bei stable (default) noch nicht installierbar.
