### ISSUE TITLE
Fix XMPP connect for new Firmware 4.15.250

### ISSUE THREAD

**Issue by Bertilax** [Pmant/ioBroker.harmony#49]
Sice Firmware 4.15.250 XMPP is enabled again and Vers. 1.1.5 is not working any more...
Confirmed working version is 0.9.3 ;)

**Comment by foxriver76** [comment]
Newest working XMPP version of the adapter should be 1.0.0 but I recongized, that https://www.npmjs.com/package/@harmonyhub/client broke something in v1.0.7, so current latest working version for this dep is 1.0.6, otherwise I am receiving
```
 [CONNECT] Could not connect to hubname: TypeError: Cannot read property 'port' of undefined
```

**Comment by Bertilax** [comment]
I tried Version 1.0.0 but it was not working - Version 0.9.3 works fine (0.9.6 was not available for download - why ever…). I tried every version back and stopped at 0.9.3.
In the future XMPP schould be the way to go - if Logitech do not touch this feature again (so they promissed ;))

**Comment by foxriver76** [comment]
0.9.3 works because the dependency was pinned to a specific version. https://github.com/AirBorne04/harmonyhub/issues/26

**Comment by foxriver76** [comment]
Yes, the content of 1.0 will also work, with a pinned dependency of harmonizing client to 1.0.6 or if this will be fixed: https://github.com/AirBorne04/harmonyhub/issues/26

**Comment by foxriver76** [comment]
As soon as this ( https://github.com/Pmant/harmonyhubws/pull/4 ) is merged, after a reinstall of the adapter it should work again with websockets.

**Comment by nob0dy80** [comment]
as long its not merged, dont forget that you have to change "Harmony_Hub" to "Harmony Hub" in your scripts/flows

**Comment by nob0dy80** [comment]
@foxriver76 
how can i pin the harmony hub client to 1.0.6 ? 
to much work to change in  all scripts the underscores :-)

**Comment by foxriver76** [comment]
V1.0.0 nehmen und in der Package JSON bei dependencies bei @harmonyhub/Client das Zirkumflex vor der Versionsnummer entfernen. Anschließend im Verzeichnis ``npm i`` ausführen.

**Comment by nob0dy80** [comment]
ah ! ok das wäre auf jeden fall der saubere weg.. ich hab einfach 1.0.0 installiert und dann die client version mit npm install @harmonyhub/client@1.0.6 drübergebügelt :-D

**Comment by Scrounger** [comment]
> 
> 
> V1.0.0 nehmen und in der Package JSON bei dependencies bei @harmonyhub/Client das Zirkumflex vor der Versionsnummer entfernen. Anschließend im Verzeichnis `npm i` ausführen.

Dein Tipp hat bei mir auch mit der Version 1.1.5 geklappt, danke!

**Comment by DanielWeeber** [comment]
Wie installiere ich denn die V1.0.0 explizit?

**Comment by DanielWeeber** [comment]
Zur Hilfe für andere, die hier lesen. Aktueller Workaround wie von @foxriver76 und @nob0dy80 erklärt wie folgt:

```
Instanz stoppen

cd /opt/iobroker
npm install iobroker.harmony@1.0.0 --production
npm install @harmonyhub/client@1.0.6
cd /opt/iobroker
iobroker upload harmony

Instanz starten
```

**Comment by DanielWeeber** [comment]
> As soon as this ( [Pmant/harmonyhubws#4](https://github.com/Pmant/harmonyhubws/pull/4) ) is merged, after a reinstall of the adapter it should work again with websockets.

It is merged, but newest version does not seem to connect. No error message after "connecting".

**Comment by foxriver76** [comment]
Problem is that it is merged but not published yet on npm.

**Comment by DanielWeeber** [comment]
Why not force the use of the GitHub repo as long it is not merged?

**Comment by foxriver76** [comment]
Both Repos are owned by Pmant and he is the only one having push access. So it doesn’t make a difference. Also I don’t like git dependencies because some people do not have git installed and more support questions will pop up.

**Comment by DanielWeeber** [comment]
Okay. Then everyone can use my fork till its published ;)

**Comment by Pmant** [comment]
Sorry for the delay guys, I just published both repos to npm.
This adapter will stick to the websocket method since the connection handling is better and we have less dependencies. 
@foxriver76 thanks a lot for the PRs.
