### ISSUE TITLE
Posibility to change the state of harmony

### ISSUE THREAD

**Issue by TeaJAge** [Pmant/ioBroker.harmony#60]
Is it posible to add a feature to change the state of the harmony hub, when someone uses the original remote. So it would be possible to use alexa and the original remote control. When the TV is turned on with the original remote, iobroker can change the state of the hub.

**Comment by foxriver76** [comment]
The adapter uses the harmony api and as you will see, if you turn on your tv with the original (non harmony) remote, also the Harmony app won’t know, that your tv has been turned on. How could it know, which activity you are currently using? You could have 10 activities including your tv. Thus, Harmony is not able to detect this and the adapter just mirrors the harmony logic.

**Comment by TeaJAge** [comment]
Ok, then it's unfortunately not possible if the api can not do that.
