### ISSUE TITLE
Ein- und Ausschalten mit einer Steckdose

### ISSUE THREAD

**Issue by McWoolf** [Pmant/ioBroker.harmony#66]
Ich habe folgendes Problem.
Ich habe meinem Heimkino eine Steckdose vorgeschaltet.
Wenn ich nun Alexa sage "Fernseher ein" wird die Steckdose eingeschaltet und auch das Heimkino richtig gestartet.
Wenn ich aber nun "Fernseher aus" sage, wird zuerst die Steckdose ausgeschaltet, somit kann das Heimkino nicht richtig runtergefahren werden. Wie kann ich das lösen?
Danke für die Hilfe

**Comment by adx-git** [comment]
Je nachdem wo du das eingestellt hast kannst du eine Verzögerung hinzufügen.

Ich habe das bei mir so gelöst, dass der ioBroker alle 10 Minuten schaut ob das Heimkino an ist, falls es nicht an ist und die Steckdose noch an ist wird die Steckdose ausgeschaltet.

**Comment by McWoolf** [comment]
Ha das ist eine gute Idee.
Ich habs über die Szene gemacht.
Kann ja iobroker selber schauen ob die on ist und dann automatisch abschalten.
Meine Güte bin ich noch ein doofy in sachen iobroker.
Danke hat mir super weitergeholfen.
