### ISSUE TITLE
Hub is busy after adapter runs some hours

### ISSUE THREAD

**Issue by thorque** [Pmant/ioBroker.harmony#8]
Hello,

I've a problem with this adapter. After running it some hours it is not possible to send a command to the hub anymore:

`2016-10-07 00:38:48.907  - info: harmony.0 hub busy, stateChange delayed: harmony.0.xxx.activities.currentStatus=0`

Do you know this? How can I fix this?
Thorsten

**Comment by Pmant** [comment]
The Adapter queues all commands as long as the hubBlocked state is true, which is the case when
- the hub is starting or stopping an activity
- another command is executed (e.g. if you set a command to 5000 then it fires for 5 seconds)
- connection to the hub is lost
- bug?!

Are there any logs before that? There are filters in the logs tab, so you can display only this adapter. 
The Harmony Hub often has disconnects and the adapter loses the xmpp connection, but it should recover automatically. When this happens a warning should show up in the logs tab (yellow).
