### ISSUE TITLE
Two Adapter for 2 Hubs is not working

### ISSUE THREAD

**Issue by RobertHerter** [Pmant/ioBroker.harmony#9]
Adding a second Hub with a second adapter is not working.
Only one a time is working, second exit with 0.:

knx.0	2017-01-30 11:43:00.278	warn	knx.0 Value recieved on unknown GA : 1/2/21
knxpi	2017-01-30 11:42:55.664	info	host.knxpi Restart adapter system.adapter.harmony.0 because enabled
knxpi	2017-01-30 11:42:55.662	error	host.knxpi instance system.adapter.harmony.0 terminated with code 0 (OK)
harmony.0	2017-01-30 11:42:55.436	info	harmony.0 hub initialized
harmony.0	2017-01-30 11:42:55.370	info	harmony.0 starting. Version 0.6.0 in /opt/iobroker/node_modules/iobroker.harmony, node: v6.9.4
host.knxpi	2017-01-30 11:42:50.986	info	instance system.adapter.harmony.0 started with pid 4306
host.knxpi	2017-01-30 11:42:50.951	info	object change system.adapter.harmony.0

**Comment by Pmant** [comment]
Two Adapters won't work since the API binds a specific port which cannot be changed. Hence support for multiple Hubs needs to be implemented into the adapter.

**Comment by agentclark** [comment]
I know only five days passed, but are there any news?
Multiple Hubs would be an awesome feature

**Comment by Pmant** [comment]
try installing this branch in ioBroker [https://github.com/Pmant/ioBroker.harmony/tarball/multihub](https://github.com/Pmant/ioBroker.harmony/tarball/multihub)

**Comment by RobertHerter** [comment]
Tried the branch and its working.

But after a while i get:
`harmony.0	2017-02-08 17:26:53.906	error	exception by stop: Cannot read property 'statesExist' of undefined
harmony.0	2017-02-08 17:26:53.901	info	terminating
harmony.0	2017-02-08 17:26:53.897	error	at Timer.listOnTimeout (timers.js:207:5)
harmony.0	2017-02-08 17:26:53.897	error	at tryOnTimeout (timers.js:237:5)
harmony.0	2017-02-08 17:26:53.897	error	at ontimeout (timers.js:365:14)
harmony.0	2017-02-08 17:26:53.897	error	at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.harmony/harmony.js:296:25)
harmony.0	2017-02-08 17:26:53.897	error	at connect (/opt/iobroker/node_modules/iobroker.harmony/harmony.js:280:18)
harmony.0	2017-02-08 17:26:53.897	error	TypeError: Cannot read property 'client' of undefined
harmony.0	2017-02-08 17:26:53.895	error	uncaught exception: Cannot read property 'client' of undefined`

**Comment by Pmant** [comment]
THanks for your report, could you test again? (install same branch again)

**Comment by RobertHerter** [comment]
So working  as expected now.

Thank you so much

**Comment by Pmant** [comment]
Will release this as 0.7.1 next week.

**Comment by RobertHerter** [comment]
So a Problem with this Version exists.

After a while one Hub is going to the state "blocked" and not out of this state.
Flooding ioBroker with permanent blocked changes.
Restarting fixes this problem, trying to get the exact error today.

**Comment by Pmant** [comment]
please try new version https://github.com/Pmant/ioBroker.harmony/tarball/multihub

**Comment by RobertHerter** [comment]
Getting the following log after a while:
`host.knxpi	2017-02-13 14:54:24.164	error	instance system.adapter.harmony.0 terminated with code 0 (OK)
harmony.0	2017-02-13 14:54:24.125	info	terminating
harmony.0	2017-02-13 14:54:24.076	info	terminating
harmony.0	2017-02-13 14:54:24.072	error	at Timer.listOnTimeout (timers.js:207:5)
harmony.0	2017-02-13 14:54:24.072	error	at tryOnTimeout (timers.js:237:5)
harmony.0	2017-02-13 14:54:24.072	error	at ontimeout (timers.js:365:14)
harmony.0	2017-02-13 14:54:24.072	error	at Explorer.executeCleanUp (/opt/iobroker/node_modules/harmonyhubjs-discover/lib/explorer.js:44:30)
harmony.0	2017-02-13 14:54:24.072	error	at Array.forEach (native)
harmony.0	2017-02-13 14:54:24.072	error	at /opt/iobroker/node_modules/harmonyhubjs-discover/lib/explorer.js:51:9
harmony.0	2017-02-13 14:54:24.072	error	at Explorer.emit (events.js:188:7)
harmony.0	2017-02-13 14:54:24.072	error	at emitOne (events.js:96:13)
harmony.0	2017-02-13 14:54:24.072	error	at Explorer. (/opt/iobroker/node_modules/iobroker.harmony/harmony.js:192:35)
harmony.0	2017-02-13 14:54:24.072	error	TypeError: Cannot read property 'reconnectTimer' of undefined
harmony.0	2017-02-13 14:54:24.070	error	uncaught exception: Cannot read property 'reconnectTimer' of undefined
harmony.0	2017-02-13 14:54:24.023	info	client ended: Schlafzimmer
mqtt.0	2017-02-13 14:54:24.031	info	send2Server harmony.0.Schlafzimmer.hubConnected[harmony/0/Schlafzimmer/hubConnected]
harmony.0	2017-02-13 14:54:24.016	warn	lost Schlafzimmer`

But it is restarting after that without Problem. If i get any further Problems i'll let you know.

**Comment by RobertHerter** [comment]
`            clientStop(hubName);
            //stop reconnect timer                                                                                                                                                            
            clearTimeout(hubs[hubName].reconnectTimer);`

Think this is the fix for the crash.

**Comment by Pmant** [comment]
Ty, please try again.

**Comment by RobertHerter** [comment]
So its working. i don't know why one Hub is loosing connection from time to time.
But now its reconnecting and working.

`mqtt.0	2017-02-13 16:33:07.584	info	send2Server harmony.0.Schlafzimmer.hubBlocked[harmony/0/Schlafzimmer/hubBlocked]
harmony.0	2017-02-13 16:33:07.535	info	synced hub config
mqtt.0	2017-02-13 16:33:06.880	info	send2Server harmony.0.Schlafzimmer.hubConnected[harmony/0/Schlafzimmer/hubConnected]
harmony.0	2017-02-13 16:33:06.862	info	connected to Schlafzimmer
harmony.0	2017-02-13 16:33:04.492	info	connecting to Schlafzimmer
mqtt.0	2017-02-13 16:33:04.444	info	send2Server harmony.0.Schlafzimmer.hubBlocked[harmony/0/Schlafzimmer/hubBlocked]
harmony.0	2017-02-13 16:33:04.401	info	discovered Schlafzimmer
mqtt.0	2017-02-13 16:33:01.815	info	send2Server harmony.0.Schlafzimmer.hubConnected[harmony/0/Schlafzimmer/hubConnected]
harmony.0	2017-02-13 16:33:01.804	info	client ended: Schlafzimmer
harmony.0	2017-02-13 16:33:01.798	warn	lost Schlafzimmer`

**Comment by Pmant** [comment]
> So its working. i don't know why one Hub is loosing connection from time to time.
But now its reconnecting and working.

probably related to Hub Wifi issues:
 https://support.myharmony.com/en-us/wi-fi-wont-connect-or-frequently-disconnects-from-the-hub

**Comment by RobertHerter** [comment]
We almost got it ;-).

Reconnect seems not always working:

harmony.0	2017-02-14 14:22:00.293	info	client ended: Wohnzimmmer
harmony.0	2017-02-14 14:22:00.266	info	keep alive failed: Error: Timed out after 5000 ms

Restarting adapter fixes it.

Looks like reconnect only work on one Harmony not on both.

**Comment by Pmant** [comment]
Thank you again!
This seems to be the rare case when keep alive failed but the discovery service didn't lose the hub. There was a bug with the reconnect call, should be fixed now.

**Comment by RobertHerter** [comment]
So switching in objects from status in activity to -1 (to switch off) this results in a Hub blocked forever.

**Comment by Pmant** [comment]
same when switching to 3 or 0? Both should result in a power off.

**Comment by RobertHerter** [comment]
Ok sorry, but the Problem is with mqtt. It only happens wen mqtt is publishing the states.
Will have a deeper look at it.
